### Web Scraping

Para obter os dados dos sites oficiais das Olímpiadas e Paralimpíadas, assim como da Wikipedia, vamos utilizar as bibliotecas `requests` e `Beautiful Soup`. Para processá-los e transformá-los em arquivos csv que facilitem nossa análise, vamos usar `pandas` e `io`.

---

In [1]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import io

#### 1 - Acessando dados da Wikipedia

Primeiro vamos extrair o quadro de medalhas das Olimpíadas

In [10]:
wiki_url = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Olímpicos"
h2_id = "Quadro_de_medalhas_dos_Jogos_Olímpicos_de_Verão"

headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (elia.dutra.sena@academico.ufpb.br)"}

response = requests.get(wiki_url, headers= headers).text
soup = BeautifulSoup(response, "html.parser")

span_titulo = soup.find(id= h2_id)
tabela_html = span_titulo.parent.find_next_sibling("table") 

html_string = str(tabela_html)

In [11]:
df_list_olympics = pd.read_html(io.StringIO(html_string))
df_olympics = df_list_olympics[0]

df_olympics

     No.                 País  Jogos  Ouro  Prata  Bronze  Total
0      1   USA Estados Unidos     29  1101    880     781   2762
1      2  URS União Soviética      9   395    319     296   1010
2      3            CHN China     12   302    227     197    726
3      4     GBR Grã-Bretanha     30   300    338     344    982
4      5           FRA França     30   240    280     298    818
..   ...                  ...    ...   ...    ...     ...    ...
150  147         ERI Eritreia      6     0      0       1      1
151  147           GUY Guiana     18     0      0       1      1
152  147           IRQ Iraque     15     0      0       1      1
153  147         MRI Maurício     10     0      0       1      1
154  147             TOG Togo     11     0      0       1      1

[155 rows x 7 columns]

Esse comando converte a tabela extraída para CSV

In [12]:
df_olympics.to_csv("medalhas_olimpiadas_wikipedia.csv", index= False, sep= ',', encoding= 'utf-8-sig')

Agora, vamos fazer o mesmo para as Paralimpíadas

In [5]:
wiki_url = "https://pt.wikipedia.org/wiki/Quadro_de_medalhas_dos_Jogos_Paralímpicos"
table_id = "mwEg"

headers = {"User-Agent": "ProjetoAnaliseDadosOlimpicos/1.0 (elia.dutra.sena@academico.ufpb.br)"}

response = requests.get(wiki_url, headers= headers).text
soup = BeautifulSoup(response, "html.parser")

tabela_html = soup.find(id= table_id)

html_string = str(tabela_html)
html_corrigido = html_string.replace('"5;"', '"5"')

Aqui tratamos a tabela que veio do wikipedia, tiramos os dados referentes as olimpíadas de inverno e a parte que somava a quatidade de medalhas totais de cada país, também mudamos o nome das colunas para ficar mais claro do que cada uma se trata.

In [ ]:
df_list_paralympics = pd.read_html(io.StringIO(html_corrigido))
df_paralympics = df_list_paralympics[0]


df_paralympics.columns = df_paralympics.columns.get_level_values(-1)

df_limpo = df_paralympics.iloc[:, :6] 

print(df_limpo.columns.tolist())
display(df_limpo.head())


df_limpo.columns = ['País', '№', 'Ouro', 'Prata', 'Bronze', 'Total']

df_paralympics = df_limpo
df_paralympics

['Time (Código\xa0COI)', '№', 'Unnamed: 2_level_1', 'Unnamed: 3_level_1', 'Unnamed: 4_level_1', 'Total']

,Time (Código COI),№,Unnamed: 2_level_1,Unnamed: 3_level_1,Unnamed: 4_level_1,Total
0,África do Sul (RSA),11,121,95,88,304
1,Alemanha (GER) [a],8,199,266,253,718
2,Alemanha Ocidental (FRG) [b],8,322,260,246,828
3,Alemanha Oriental (GDR) [c],1,0,3,1,4
4,Angola (ANG),6,4,3,1,8

                             País   №  Ouro  Prata  Bronze  Total
0             África do Sul (RSA)  11   121     95      88    304
1              Alemanha (GER) [a]   8   199    266     253    718
2    Alemanha Ocidental (FRG) [b]   8   322    260     246    828
3     Alemanha Oriental (GDR) [c]   1     0      3       1      4
4                    Angola (ANG)   6     4      3       1      8
..                            ...  ..   ...    ...     ...    ...
127             Uzbequistão (UZB)   4    16     12      23     51
128               Venezuela (VEN)   7     4      7      13     24
129                  Vietnã (VIE)   4     1      2       2      5
130                Zimbabwe (ZIM)   9     2      9       6     17
131                        Totais  16  7513   7298    7336  22147

[132 rows x 6 columns]

E por fim, também convertemos a tabela para CSV

In [14]:
df_paralympics.to_csv("medalhas_paralimpiadas_wikipedia.csv", index= False, sep= ',', encoding= 'utf-8-sig')

#### 2 - Acessando sites oficiais das Olimpíadas e Paralimpíadas

In [ ]:
#IN PROGRESS...